//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SStack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerSegment
    {
        public short CustomerSegmentId { get; set; }
        public string Segment { get; set; }
        public string Code { get; set; }
    }
}
