//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SStack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwOrder
    {
        public int EntryId { get; set; }
        public int ProductId { get; set; }
        public int Qty { get; set; }
        public int CustomerOrderId { get; set; }
        public System.DateTime EntryDate { get; set; }
        public double FinalPrice { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string Id { get; set; }
        public string OrderDescription { get; set; }
        public string OrderStatus { get; set; }
        public string ProductName { get; set; }
        public double Price { get; set; }
        public double MaxDiscount { get; set; }
        public double MinDiscount { get; set; }
    }
}
